apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mnj3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-mnj3
    app.kubernetes.io/part-of: test-rhtap-88-app
  name: devfile-sample-code-with-quarkus-mnj3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mnj3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mnj3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-88-tenant/test-rhtap-88-app/devfile-sample-code-with-quarkus-mnj3@sha256:b22b886ff432b542fad958496d5e7f3a6c4e16df33e3be84af2f76ced35511e5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
